services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blog_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=blog_redis_secure_password_2024
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: blog_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: blog_redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=blog_redis_secure_password_2024
    volumes:
      - redis_data:/data
    command: redis-server --requirepass blog_redis_secure_password_2024 --appendonly yes
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
